package com.baddysays.saylat.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal fun lightOnlyPalettes(): Map<AppThemeId, ThemePalette> = mapOf(
    AppThemeId.PAPER to ThemePalette(
        preview = Color(0xFFF5F0E6),
        light = lightColorScheme(
            primary = Color(0xFF8B5E34),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFF5E6D3),
            onPrimaryContainer = Color(0xFF4A3728),
            secondary = Color(0xFFA68A64),
            tertiary = Color(0xFF6B7280),
            background = Color(0xFFFAF6EF),
            surface = Color(0xFFFFFCF7),
            surfaceVariant = Color(0xFFEDE4D4),
            onBackground = Color(0xFF2C2419),
            onSurface = Color(0xFF2C2419),
        ),
        dark = lightColorScheme(
            primary = Color(0xFF8B5E34),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFF5E6D3),
            onPrimaryContainer = Color(0xFF4A3728),
            secondary = Color(0xFFA68A64),
            background = Color(0xFFFAF6EF),
            surface = Color(0xFFFFFCF7),
            surfaceVariant = Color(0xFFEDE4D4),
            onBackground = Color(0xFF2C2419),
            onSurface = Color(0xFF2C2419),
        ),
    ),
    AppThemeId.SNOW to ThemePalette(
        preview = Color(0xFFE8F4FC),
        light = lightColorScheme(
            primary = Color(0xFF2563EB),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFDBEAFE),
            onPrimaryContainer = Color(0xFF1E3A8A),
            secondary = Color(0xFF38BDF8),
            tertiary = Color(0xFF64748B),
            background = Color(0xFFF8FAFC),
            surface = Color.White,
            surfaceVariant = Color(0xFFE2E8F0),
            onBackground = Color(0xFF0F172A),
            onSurface = Color(0xFF0F172A),
        ),
        dark = lightColorScheme(
            primary = Color(0xFF2563EB),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFDBEAFE),
            onPrimaryContainer = Color(0xFF1E3A8A),
            background = Color(0xFFF8FAFC),
            surface = Color.White,
            surfaceVariant = Color(0xFFE2E8F0),
            onBackground = Color(0xFF0F172A),
            onSurface = Color(0xFF0F172A),
        ),
    ),
    AppThemeId.LEMON to ThemePalette(
        preview = Color(0xFFFEF9C3),
        light = lightColorScheme(
            primary = Color(0xFFCA8A04),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFFEF08A),
            onPrimaryContainer = Color(0xFF713F12),
            secondary = Color(0xFFEAB308),
            tertiary = Color(0xFF65A30D),
            background = Color(0xFFFFFBEB),
            surface = Color(0xFFFFFFF7),
            surfaceVariant = Color(0xFFFEF3C7),
            onBackground = Color(0xFF422006),
            onSurface = Color(0xFF422006),
        ),
        dark = lightColorScheme(
            primary = Color(0xFFCA8A04),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFFEF08A),
            onPrimaryContainer = Color(0xFF713F12),
            background = Color(0xFFFFFBEB),
            surface = Color(0xFFFFFFF7),
            surfaceVariant = Color(0xFFFEF3C7),
            onBackground = Color(0xFF422006),
            onSurface = Color(0xFF422006),
        ),
    ),
    AppThemeId.LILAC to ThemePalette(
        preview = Color(0xFFEDE9FE),
        light = lightColorScheme(
            primary = Color(0xFF7C3AED),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFEDE9FE),
            onPrimaryContainer = Color(0xFF4C1D95),
            secondary = Color(0xFFA78BFA),
            tertiary = Color(0xFFDB2777),
            background = Color(0xFFFAF5FF),
            surface = Color.White,
            surfaceVariant = Color(0xFFF3E8FF),
            onBackground = Color(0xFF3B0764),
            onSurface = Color(0xFF3B0764),
        ),
        dark = lightColorScheme(
            primary = Color(0xFF7C3AED),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFEDE9FE),
            onPrimaryContainer = Color(0xFF4C1D95),
            background = Color(0xFFFAF5FF),
            surface = Color.White,
            surfaceVariant = Color(0xFFF3E8FF),
            onBackground = Color(0xFF3B0764),
            onSurface = Color(0xFF3B0764),
        ),
    ),
    AppThemeId.CORAL to ThemePalette(
        preview = Color(0xFFFFE4E6),
        light = lightColorScheme(
            primary = Color(0xFFE11D48),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFFFE4E6),
            onPrimaryContainer = Color(0xFF9F1239),
            secondary = Color(0xFFFB7185),
            tertiary = Color(0xFFF97316),
            background = Color(0xFFFFF1F2),
            surface = Color.White,
            surfaceVariant = Color(0xFFFECDD3),
            onBackground = Color(0xFF881337),
            onSurface = Color(0xFF881337),
        ),
        dark = lightColorScheme(
            primary = Color(0xFFE11D48),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFFFE4E6),
            onPrimaryContainer = Color(0xFF9F1239),
            background = Color(0xFFFFF1F2),
            surface = Color.White,
            surfaceVariant = Color(0xFFFECDD3),
            onBackground = Color(0xFF881337),
            onSurface = Color(0xFF881337),
        ),
    ),
)
